name: gasolinera_puma
description: Proyecto de suma ambicion
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  carousel_slider: ^4.2.1
  url_launcher: ^6.2.1
  popover: ^0.2.8+2
  flutter_map: ^0.13.0

dev_dependencies:
  flutter_launcher_icons: "^0.9.3"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

##flutter icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/gas.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/gas.png
    - assets/promos/
    - assets/icon/